# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15.5

# Mod Properties
mod_id = warpspeed
mod_version = 3.0.0
maven_group = uk.co.finleyofthewoods
archives_base_name = WarpSpeed

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.148.0+26.1.2
